export const DANGER_CHECKBOX_CHANGE = 'DANGER_CHECKBOX_CHANGE'
export const DISTANCE_RADIO_CHANGE = 'DISTANCE_RADIO_CHANGE'
export const APP_SCROLL_DOWN = 'APP_SCROLL_DOWN'
export const PAGE_CHANGE = 'PAGE_CHANGE'
